### ISSUE TITLE
Get Help Page: Why is there a yellow bar at the bottom?  Is there a missing section on that page?

### ISSUE THREAD

**Issue by chuckb1789** [BootcampersCollective/a-womans-place#13]

**Comment by AlanBCole** [comment]
There is information being pointed to but that information does not exist and that is why the bar/div is blank. There is a community_resources array, which is empty, coming back in the server's response to the $http request started on the controller.main.js line 39. I think this means that it has to be handled from the CMS side.

Is there someone providing the content via butter cms for the site that could add this for us? I'll see if I can add something for now.

**Comment by AlanBCole** [comment]
There was a problem in this issue... (it may show up in other issues as well).

Brian, Kirsten and I (Alan) were working on this today

After adding text to butter in the community resources fields, HTML tags were showing up in the community resources section on the web page. This happened in other places as well, and the text was unformatted.

In the butter CMS the relevant field was set as WYSIWYG, which gives a word processor type of functionality, good for someone maintaining the data/text. However when the text from WYSIWYG text fields is sent as HTML to AngularJS it is 'sanitized' as a standard safety/security measure that angular always takes and displayed as a simple unformatted string.

The HTML has to be marked as safe to display properly using ng-bind-html directive on the relevant HTML element, for example ng-bind-html="main.communityResources".

The controller then has to be set:
 main.communityResources = main.communityResources =
$sce.trustAsHtml(main.awp.community_resources[0].description); 

I did the same thing for the other text on the page and all is displaying well now!

Sorry for the long comment, just wanted to write it down in case it was a problem for anyone else!
