### ISSUE TITLE
Learn More: Change the blue and yellow sections from stacked to side by side.

### ISSUE THREAD

**Issue by chuckb1789** [BootcampersCollective/a-womans-place#31]

**Comment by chuckb1789** [comment]
When view on mobile view, these should still remain stacked though.

**Comment by chuckb1789** [comment]
Columns should be in BLUE, YELLOW order.

**Comment by AlanBCole** [comment]
I got the side to side bit/stacking with bootstrap classes, but there are some other things to iron out. I will keep working on those.
