### ISSUE TITLE
Home Page: Link “Learn More” button to updated services list on “Get Help” page.

### ISSUE THREAD

**Issue by chuckb1789** [BootcampersCollective/a-womans-place#8]

**Comment by smokeyblues** [comment]
Is this referring to the learn more button in the 'More Than a Shelter' section under the carousel? Or is it referring to the one from the 'More Than Physical Abuse' Section that was part of issue 7?

**Comment by chuckb1789** [comment]
Hey Aaron, I will ask her about this one. It seems like too much ambiguity to make a determination either way. I'll let you know what I hear from her.
